url: "https://yanivle.github.io/"

author:
  name:           	 Yaniv Leviathan
  url:            	 yanivle.github.io
  facebook:          yanivle
  linkedin:          yaniv-leviathan

site:
  author:
    facebook:        yanivle
    linkedin:        yaniv-leviathan
