baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
# icon:                /assets/images/icon.png

author:
  name:           	 Yaniv Leviathan
  url:            	 yanivle.github.io
  facebook:          yanivle
  linkedin:          yaniv-leviathan

site:
  discuss:           yanivle
  author:
    twitter:         yanivle
    facebook:        yanivle
    linkedin:        yaniv-leviathan
    dribble:         yanivle
    pinterest:       yanivle
    kiva:            yanivle
  rss:               yanivle
