url: "https://yanivle.github.io/"

author:
  name:           	 Yaniv Leviathan
  url:            	 yanivle.github.io
  facebook:          yanivle
  linkedin:          yaniv-leviathan
  twitter:           yanivle

site:
  author:
    facebook:        yanivle
    linkedin:        yaniv-leviathan
    twitter:           yanivle

plugins:
  - jekyll-sitemap